# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='attr',
        ),
        migrations.AddField(
            model_name='invoice',
            name='attributes',
            field=models.ManyToManyField(related_name='invoices', to='demo.Attribute'),
        ),
    ]
